### PR TITLE
test: switch to GitHub Actions

### PR DESCRIPTION
**Pull request by greatislander**
As implemented in [662a99ac312cd8cf2197d9988dc24311f064ab6a](https://github.com/accessibility-exchange/laravel-multilingual-routes/commit/662a99ac312cd8cf2197d9988dc24311f064ab6a), this PR adds a GitHub Actions test for this package to replace the Travis tests.

### CODE REVIEW

**Review by chinleung — APPROVED** [review]

**Comment by chinleung** [comment]
@greatislander Can you fix the conflicts here please? :)

**Comment by greatislander** [comment]
@chinleung done!

**Comment by greatislander** [comment]
On my fork, it looks like [PHP 8.1 with `prefer-lowest` fails](https://github.com/accessibility-exchange/laravel-locales/runs/5141328419?check_suite_focus=true). Wondering if that means I should drop support for older Laravel versions in a separate PR?

**Comment by chinleung** [comment]
> On my fork, it looks like [PHP 8.1 with `prefer-lowest` fails](https://github.com/accessibility-exchange/laravel-locales/runs/5141328419?check_suite_focus=true). Wondering if that means I should drop support for older Laravel versions in a separate PR?

Yeah, could you update it to drop older version as well please? I'll release it as v2.

**Comment by chinleung** [comment]
I've made two new branches `v1` and `v2`. Could remove Laravel 9 from `v1` and remove anything below PHP 8 from `v2`. 😄

**Pull request merged**
